// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  slice_test: dynamic(() => import("./SliceTest")),
  test: dynamic(() => import("./Test")),
};
