// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
    app: dynamic(() => import("./App")),
    block1: dynamic(() => import("./Block1")),
};
